urls.py
from puzzlaef.views import *
from django.conf import settings
from puzzlaef.dajaxice.core import dajaxice_autodiscover
from django.conf.urls.defaults import patterns, include, url
from django.contrib import admin
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from django.views.generic.simple import direct_to_template

dajaxice_autodiscover()

# Uncomment the next two lines to enable the admin:
admin.autodiscover()

urlpatterns = patterns('',
    # Examples:
    # url(r'^$', 'puzzlaef.views.home', name='home'),
    # url(r'^puzzlaef/', include('puzzlaef.foo.urls')),

    # Uncomment the admin/doc line below to enable admin documentation:
    url(r'^admin/doc/', include('django.contrib.admindocs.urls')),

    # Uncomment the next line to enable the admin:

    url(r'^$', start), 
	url(r'^upload/makeMove', make_move),
	url(r'^upload/profile', upload_profile),
    url(r'^upload/theme', upload_theme),
	url(r'^upload/newPuzzle', new_puzzle),
    url(r'^admin/', include(admin.site.urls)),
    url(r'^profile/$', show_profile),  
    (r'^accounts/', include('puzzlaef.registration.backends.default.urls')), 
    (r'^dajaxice/', include('puzzlaef.dajaxice.urls')), #% settings.DAJAXICE_MEDIA_PREFIX, include('puzzlaef.dajaxice.urls')),

)

urlpatterns += staticfiles_urlpatterns()

puzzle/models.py
from django.conf import settings
from django.core.files import File
from django.core.files.base import ContentFile
from django.db import models
from django.shortcuts import get_object_or_404
from django.template.defaultfilters import slugify
from os.path import join
from tempfile import *
from django.contrib.auth.models import User
from django.db import models
from django.template.loader import render_to_string
from puzzlaef.settings import *
from puzzlaef.main.models import UserProfile
from string import split

import datetime
import django.core.files.uploadhandler
import os
import time
import zipfile

try:
    import Image
    import ImageFile
    import ImageFilter
    import ImageEnhance
except ImportError:
    try:
        from PIL import Image
        from PIL import ImageFile
        from PIL import ImageFilter
        from PIL import ImageEnhance
    except ImportError:
        raise ImportError('Photologue was unable to import the Python Imaging Library. Please confirm it`s installed and available on your current Python path.')

try:
    import Image
    import ImageFile
    import ImageFilter
    import ImageEnhance
except ImportError:
    try:
        from PIL import Image
        from PIL import ImageFile
        from PIL import ImageFilter
        from PIL import ImageEnhance
    except ImportError:
        raise ImportError('Photologue was unable to import the Python Imaging Library. Please confirm it`s installed and available on your current Python path.')

# Create your models here.
#class Puzzle:
#    
#    admin = models.ForeignKey(Member, help_text = 'Administrator of this event')

def get_image_path(instance, filename):
    return os.path.join('photos', str(instance.user.username), '' + time.strftime("%Y-%m-%d-") + slugify(split(filename,'.')[0])+ '.' +split(filename,'.')[1])

class Photo(models.Model):
    title = models.CharField(max_length=200)
    width = models.IntegerField()
    height = models.IntegerField()
    isTheme = models.BooleanField(default = False);
    title_slug = models.SlugField(help_text=('A "slug" is a unique URL-friendly title for an object.'))
    image = models.ImageField(upload_to=get_image_path, height_field='height', width_field='width')
    user = models.ForeignKey(User, related_name = "user")

    def save(self, *args, **kwargs):
        print 'er'
        super(Photo, self).save(*args, **kwargs)
        self.im_resize()
        print 'er'
        im = Image.open(self.image.path)
        im.thumbnail((250,250), Image.ANTIALIAS)
        print 'er'
        path, fnext = os.path.split(self.image.name)
        fn, ext = os.path.splitext(fnext)
        thumb_path = join(MEDIA_ROOT, path, 'thumbnails/')
        if not os.path.exists(thumb_path):
            os.makedirs(thumb_path)
        print 'er'
        im.save(thumb_path + fn + '-thumb' + ext, 'JPEG')
        self.thumbLoc = self.get_thumb_url()
        self.pictureLoc = self.get_url()

    def im_resize(self):
        new_image = Image.open(self.image.path)
        new_image.thumbnail((700, 500), Image.ANTIALIAS)
        os.remove(self.image.path)
        new_image.save(self.image.path)
        
    def get_thumb(self):
        path, fnext = os.path.split(self.image.name)
        fn, ext = os.path.splitext(fnext)
        thumb_path = join(path, 'thumbnails/')
        return thumb_path + fn + '-thumb' + ext

    def get_thumb_url(self):
        return join(MEDIA_URL, self.get_thumb())

    def get_url(self):
        return join(MEDIA_URL, self.image.name)
            
    def delete(self):
        os.remove(self.image.path)
        os.remove(join(MEDIA_ROOT, self.get_thumb()))
        super(Photo,self).delete()
        
    def __str__(self):
        return self.title
    
    def __unicode__(self):
        return self.title
    
    def getAsString(self):
        return render_to_string("puzzle/pictureThumb.html", {'picture':self})

CONSTRAINT_CHOICES = (
    ('C', 'Color'),
    ('T', 'Theme'),
)

class Puzzle(models.Model):
	title = models.CharField(max_length=200)
	player1 = models.ForeignKey(User, related_name = "player1")
	player2 = models.ForeignKey(User, related_name = "player2", null = True)
	turn = models.ForeignKey(User, related_name = "turn", null = True)
	time_modified = models.DateTimeField(auto_now=True)
	
	def __str__(self):
		return "{0}, {1} and {2}, {3}".format(self.player1, self.player1.get_profile().location, self.player2, self.player2.get_profile().location)
    
	def __unicode__(self):
		return "{0}, {1} and {2}, {3}".format(self.player1, self.player1.get_profile().location, self.player2, self.player2.get_profile().location)

class PuzzlePiece(models.Model):
	helper = models.ForeignKey(User, related_name = "PieceHelper", null=True)
	puzzle = models.ForeignKey(Puzzle)
	owner = models.ForeignKey(User, related_name = "PieceOwner")
	constraint = models.CharField(max_length=1, choices=CONSTRAINT_CHOICES)
	photo = models.ForeignKey(Photo)
	time_modified = models.DateTimeField(auto_now=True)
	needs_help = models.BooleanField()
	
	def location(self):
		return UserProfile.objects.get(user=self.owner).location

class Comment(models.Model):
	piece = models.ForeignKey(PuzzlePiece, related_name ="commentPiece")
	text = models.TextField()
	time_made = models.DateTimeField(auto_now=True)
	commenter = models.ForeignKey(User)
	
	
	def __str__(self):
		return self.text

puzzle/views.py
# Create your views here.

templates/puzzle/normalPiece.html
<a onclick="showPiece({{piece.id}})" href="#" class="thumbnail piece">
	<div class={{ constraintClass }}>{{ leftPiece.get_constraint_display }}</div> 
	<img class="piece-picture" src={{ piece.photo.get_thumb_url }} />
</a>

templates/puzzle/pickTheme.html
<div class="title blue"> Pick a theme for your Puzzlaef </div>
<div class="helper-text">
	The theme decides what pictures you and <i>{{ startWith }}</i> can use in this Puzzlaef.<br />
	Don't worry, you can change the theme later in the Puzzlaef too.
</div>

<div id="file-uploader">	       
</div>

<form id="hidden_form" style="display:none">
{% csrf_token %}
</form>

</div>
<script>
$('.fileUpload').fileUploader();
</script>

{{ pictureGrid }}

<div class="button blue" id="begin_button" style="float: none; width: 130px; margin-left: auto; margin-right: auto">Begin the Puzzlaef!</div>

templates/puzzle/pictureGrid.html
<div class="pictureGrid">
	{% for picture in pictureSet %}
		{{ picture }}
	{% endfor %}
</div>

<form id="hidden_form" style="display:none">
{% csrf_token %}
</form>

templates/puzzle/pictureThumb.html
<div class='thumbWrapper'>
	<img class='thumb' src={{ picture.get_thumb_url }} alt={{ picture.title }} height='150' width='150' />
	<div class='thumbLabel'>{{ picture.title }}</div>
</div>

templates/puzzle/pieceComments.html
<div id="piece-comments" class="span2">
	{% for comment in comments %}
  <div class="comment">
		<blockquote>
		  <p>{{ comment.text }}</p>
		  <small> {{ comment.commenter }} </small>
		</blockquote>
	</div>
	{% endfor %}
	<textarea id="new-comment-textarea" placeholder="Comment about the photo or how well the piece fits into the puzzle..." id="textarea" rows="3"></textarea>
	<button id="new-comment-button" class="btn">
	  Comment
	</button>
</div>

templates/puzzle/pieceView.html
<div class="container-fluid" id="pieceView">
  <div class="row-fluid">
		<div class="span10">
	      <div class="row-fluid">
					<div class="span12">
						<ul class="thumbnails">
							{% if prevPiece %} 
							<li class="span2">
								<a href='#' onClick='showPiece( {{ prevPiece.id }} )' class="thumbnail">
								    <img class="piece-view-picture" src={{ prevPiece.photo.get_thumb_url }} />
						    </a>
							</li>
							{% endif %}
						  <li class="span7">
								<div class="thumbnail">
								    <img class="piece-view-picture" src={{ piece.photo.get_url }} />
						    </div>
							</li>
							{% if nextPiece %} 
							<li class="span2">
								<a href='#' onClick='showPiece( {{ nextPiece.id }} )' class="thumbnail">
								    <img class="piece-view-picture" src={{ nextPiece.photo.get_thumb_url }} />
						    </a>
							</li>
							{% endif %}
						</ul>
					</div>
		    </div>
	  </div>
    {% include 'puzzle/pieceComments.html' %}
  </div>
</div>

templates/puzzle/pieceViewModal.html
<div class="modal" id="pieceViewModal">
  <div class="modal-header">
    <a class="close" data-dismiss="modal">×</a>
				<h2 style="display:inline-block">{{ piece.puzzle.player1.username }} <h6 style="display:inline-block"> {{ piece.puzzle.player1.get_profile.location }}</h6></h2>
					 <h1 style="display:inline-block">+</h1>
					<h2 style="display:inline-block">{{ piece.puzzle.player2.username }} <h6 style="display:inline-block"> {{ piece.puzzle.player2.get_profile.location }}</h6></h2>
  </div>
  <div class="modal-body" style="max-height:none !important">
    {% include 'puzzle/pieceView.html' %}
  </div>
</div>

templates/puzzle/plusButton.html
var uploader = new qq.FileUploader({
    element: document.getElementById('plus-button'),
    action: 'upload/profile',
	allowedExtensions: ['jpg', 'jpeg', 'png', 'gif'],
	template: '<div class="qq-uploader">' + 
            '<div class="qq-upload-drop-area"><span>Drop files here to upload</span></div>' +
            '<div class="qq-upload-button button blue" style="float:none; font-size:50px">+</div>' +
            '<ul class="qq-upload-list"></ul>' + 
         '</div>',
    debug: true
});

templates/puzzle/puzzle.html
<div class='puzzle' id="puzzle{{ puzzle.id }}">
	<div class="names">
		<div class="name1 {% if request %} {% ifequal request.user puzzle.player1 %} user-name {% endifequal %}{% endif %}">
			<h3>{{ puzzle.player1.username }} </h3>
			<h6 style="color:black">{{ puzzle.player1.get_profile.location }}</h6>
		</div>
		<div class="name2 {% if request %} {% ifequal request.user puzzle.player2 %} user-name {% endifequal %}{% endif %}">
			<h3>{{ puzzle.player2.username }} </h3>
			<h6 style="color:black">{{ puzzle.player2.get_profile.location }}</h6>
		</div>
	</div>
	<div class="puzzle-pieces">
		<div class="{{leftPiecesName}} {% if request %} {% ifequal request.user puzzle.player1 %} user-piece-side {% endifequal %}{% endif %}">
			{% for leftPiece in leftPieces %}
			    {{ leftPiece }}
			{% endfor %}
		</div>
		<div class="{{rightPiecesName}} {% if request %} {% ifequal request.user puzzle.player2 %} user-piece-side {% endifequal %}{% endif %}">
			{% for rightPiece in rightPieces %}
			    {{ rightPiece }}
			{% endfor %}
		</div>
	</div>
</div>

templates/puzzle/startPuzzleContent.html
<form id="hidden_form" style="display:none">
{% csrf_token %}
</form>
<div class="well">
	<div class="row-fluid">
		<div class="span2">
			<h3>Join a puzzle that someone else has started!</h3>
		</div>
		<div class="span10">
			<ul class="thumbnails">
			  {% for piece in openPuzzlePieces %}
			  <li class="span2">
			    <div class="thumbnail open-puzzle-thumbnail">
			      <img class="thumbnail-image" src="{{ piece.photo.get_thumb_url }}" alt="">
			      <h4 class="open-puzzle-location">{{ piece.location }}</h4>
			      <div class="open-puzzle-user">{{ piece.owner }}</div>
						<div class="open-puzzle-id">{{ piece.puzzle.id }}</div>
						<div class="btn btn-primary play-button">
							Join
						</div>
			    </div>
			  </li>
			  {% endfor %}
			</ul>
		</div>
	</div>

	<div class="row">
		<div class="span2" style="text-align:center; padding-bottom:20px; color: #AAA">
			<h1> or </h1>
		</div>
	</div>

	<div class="row-fluid">
		<div class="span2">
			<h3> Start a new puzzle yourself!</h3>
		</div>
		<div class="span10">
			<div id="start-puzzle-file-uploader" data-loading-text="starting new puzzle...">
				Upload a new Photo
			</div>
		</div>
	</div>

</div>

templates/puzzle/theirTurnPiece.html
<a class="thumbnail piece">
	<div id="question-mark">*</div>
	<div class="thumbLabel puzzleThumb">Its their turn to start the round!</div>
</a>

templates/puzzle/uploadButton.html
var uploader = new qq.FileUploader({
element: document.getElementById('{{ id }}'),

action: '{{ action }}',

{{ onCompleteCallback }}

allowedExtensions: ['jpg', 'jpeg', 'png', 'gif'],

{% if params %}
  {% autoescape off %}
		params: {{ params }},
	{% endautoescape %}
{% endif %}

template: '<div class="qq-uploader">' + 
           '<div class="qq-upload-drop-area"><span>Drop files here to upload</span></div>' +
           '<div class="qq-upload-button btn btn-primary btn-large" data-loading-text="uploading..." style="{{ style }}">{{ label }}</div>' +
           '<ul class="qq-upload-list"></ul>' + 
        '</div>',

debug: true
});

templates/puzzle/yourTurnPiece.html
<form id="hidden_form" style="display:none">
{% csrf_token %}
</form>
<a class="thumbnail piece">
	<div id="plus-button{{puzzle_id}}">+</div>
	<div class="thumbLabel puzzleThumb">Its your turn! Add your Picture!</div>
</a>

{% if uploadButtonScript %}
	<script>
			{{ uploadButtonScript }}
	</script>
{% endif %}